diff --git a/ui/main.js b/ui/main.js
index b03aaa2e2b204856d6bce47ac5bed4dfb0a17493..09724e5b68ab3647fa6b90d5a6b93bc27844e8c4 100644
--- a/ui/main.js
+++ b/ui/main.js
@@ -1,199 +1,7 @@
 (function(){
   "use strict";
 
-  const EIKON = window.EIKON;
-  const root = document.getElementById("eikon-root");
-
-  function renderLogin(){
-    root.innerHTML = "";
-    const card = EIKON.el("div", { class:"card login-card" });
-
-    const title = EIKON.el("div", { class:"login-title" },
-      EIKON.el("div", { class:"eikon-logo" }, "E"),
-      EIKON.el("div", null,
-        EIKON.el("b", null, "EIKON"),
-        EIKON.el("div", { class:"sub" }, "Sign in to your registers")
-      )
-    );
-
-    const fEmail = EIKON.el("div", { class:"field" },
-      EIKON.el("label", null, "Email"),
-      EIKON.el("input", { type:"email", id:"login_email", autocomplete:"username", placeholder:"you@example.com" })
-    );
-    const fPass = EIKON.el("div", { class:"field" },
-      EIKON.el("label", null, "Password"),
-      EIKON.el("input", { type:"password", id:"login_password", autocomplete:"current-password", placeholder:"••••••••" })
-    );
-
-    const btn = EIKON.el("button", { class:"btn primary", onclick: onLogin }, "Login");
-
-    card.append(title, fEmail, fPass, EIKON.el("div", { style:"height:10px" }), btn);
-    root.append(EIKON.el("div", { class:"login-shell" }, card));
-
-    async function onLogin(){
-      const email = (card.querySelector("#login_email").value || "").trim();
-      const password = (card.querySelector("#login_password").value || "");
-      if (!email || !password){
-        EIKON.toast("Enter email + password", "warn");
-        return;
-      }
-      btn.disabled = true;
-      btn.textContent = "Signing in...";
-      try{
-        await EIKON.login(email, password);
-        await boot();
-      } catch(e){
-        EIKON.toast(e && e.message ? e.message : "Login failed", "err");
-      } finally {
-        btn.disabled = false;
-        btn.textContent = "Login";
-      }
-    }
-  }
-
-  function moduleList(){
-    const mods = EIKON.modules || {};
-    const out = [];
-    for (const [k, v] of Object.entries(mods)){
-      if (!v || !v.meta) continue;
-      out.push({ key:k, meta:v.meta });
-    }
-    out.sort((a,b)=>(a.meta.order||999)-(b.meta.order||999));
-    return out;
-  }
-
-  function getRoute(){
-    const h = (location.hash || "").replace(/^#/,"").trim();
-    if (!h) return "";
-    return h;
-  }
-
-  function setRoute(k){
-    location.hash = "#" + k;
-  }
-
-  function renderShell(user){
-    root.innerHTML = "";
-
-    const shell = EIKON.el("div", { class:"eikon-shell" });
-    if (EIKON.sidebarGetCollapsed()) shell.classList.add("sidebar-collapsed");
-
-    const sidebar = EIKON.el("div", { class:"eikon-sidebar" });
-
-    const brand = EIKON.el("div", { class:"eikon-brand" },
-      EIKON.el("div", { class:"eikon-logo" }, "E"),
-      EIKON.el("div", { class:"title" },
-        EIKON.el("b", null, "EIKON"),
-        EIKON.el("span", null, "Pharmacy Registers")
-      )
-    );
-
-    const nav = EIKON.el("div", { class:"eikon-nav" });
-
-    const footer = EIKON.el("div", { class:"eikon-sidebar-footer" },
-      EIKON.el("div", { class:"eikon-userline" },
-        EIKON.el("b", null, user.email || ""),
-        EIKON.el("span", null, (user.org_name || "") + " · " + (user.location_name || ""))
-      ),
-      EIKON.el("button", { class:"eikon-logout", onclick: ()=>{
-        EIKON.logout();
-        renderLogin();
-      }}, "Logout")
-    );
-
-    sidebar.append(brand, nav, footer);
-
-    const main = EIKON.el("div", { class:"eikon-main" });
-
-    const topbar = EIKON.el("div", { class:"eikon-topbar" },
-      EIKON.el("div", { style:"display:flex;align-items:center;gap:10px;min-width:0" },
-        EIKON.el("button", { class:"btn ghost", title:"Toggle sidebar", onclick: ()=>{
-          const collapsed = shell.classList.toggle("sidebar-collapsed");
-          EIKON.sidebarSetCollapsed(collapsed);
-        }}, "☰"),
-        EIKON.el("div", { style:"min-width:0" },
-          EIKON.el("div", { style:"font-weight:900;line-height:1.1;white-space:nowrap;overflow:hidden;text-overflow:ellipsis" }, "Eikon"),
-          EIKON.el("div", { style:"color:rgba(255,255,255,.62);font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis" },
-            (user.org_name || "") + " · " + (user.location_name || "") + " · " + (user.email || "")
-          )
-        )
-      ),
-      EIKON.el("div", { style:"display:flex;align-items:center;gap:10px" },
-        EIKON.el("span", { class:"pill" }, "Role: " + (user.role || ""))
-      )
-    );
-
-    const content = EIKON.el("div", { id:"eikon-content", class:"grid", style:"gap:14px" });
-
-    main.append(topbar, content);
-    shell.append(sidebar, main);
-    root.appendChild(shell);
-
-    const mods = moduleList();
-    if (mods.length === 0){
-      nav.append(
-        EIKON.el("div", { class:"eikon-navbtn" },
-          EIKON.el("div", { class:"eikon-navicon" }, "…"),
-          EIKON.el("div", { class:"eikon-navtext" },
-            EIKON.el("b", null, "No modules"),
-            EIKON.el("span", null, "Nothing loaded yet")
-          )
-        )
-      );
-      content.append(EIKON.el("div", { class:"card" }, EIKON.el("h2", null, "Module not available.")));
-      return;
-    }
-
-    for (const m of mods){
-      const btn = EIKON.el("button", { class:"eikon-navbtn", onclick: ()=>setRoute(m.key) },
-        EIKON.el("div", { class:"eikon-navicon" }, m.meta.icon || "■"),
-        EIKON.el("div", { class:"eikon-navtext" },
-          EIKON.el("b", null, m.meta.title || m.key),
-          EIKON.el("span", null, m.meta.subtitle || "")
-        )
-      );
-      btn.dataset.mod = m.key;
-      nav.appendChild(btn);
-    }
-
-    function renderRoute(){
-      const k = getRoute() || mods[0].key;
-      const mod = EIKON.modules[k];
-
-      nav.querySelectorAll(".eikon-navbtn").forEach(b=>{
-        b.classList.toggle("active", b.dataset.mod === k);
-      });
-
-      content.innerHTML = "";
-      if (!mod || typeof mod.render !== "function"){
-        content.append(EIKON.el("div", { class:"card" }, EIKON.el("h2", null, "Module not available.")));
-        return;
-      }
-
-      try{
-        mod.render(content, user);
-      } catch(e){
-        content.append(
-          EIKON.el("div", { class:"card" },
-            EIKON.el("h2", null, "Module crashed"),
-            EIKON.el("p", { class:"sub" }, (e && (e.stack || e.message)) ? String(e.stack || e.message) : "Unknown error")
-          )
-        );
-      }
-    }
-
-    window.addEventListener("hashchange", renderRoute);
-    renderRoute();
-  }
-
-  async function boot(){
-    const me = await EIKON.ensureMe();
-    if (!me){
-      renderLogin();
-      return;
-    }
-    renderShell(me);
+  if (window.EIKON && typeof window.EIKON.boot === "function") {
+    window.EIKON.boot("#eikon-root");
   }
-
-  boot();
 })();
